---
layout: post
title:  "Yet Another Day"
---
another day here in durango and i finally took a little hike. i tried dallas trail a week ago and accidentally cheated myself out of a real hike by finding a little hidden trail… that went straight to the parking lot. cool short cut i guess. today i attempted the rim/lions den trail which is super easy, if you’re not terribly out of shape. 529 steps that go straight up to the college from the quaint little houses downtown. i got to step 230 and then decided on the switchbacks which get you to the same place. the view from the top, which is the view i will enjoy being a prof at ‘the fort’, is pretty idyllic. the town looks like a miniature set for a model train. ive been trying to reach out more, make friends or whatever. trying out new coffee shops is a method? i dunno i rarely speak to anyone when i’m out unless they’ve been drinking. 
yesterday i hit 60 days without alcohol or any substance other than nicotine. ahhh nicotine, thanks for being in my life. i’ve been eating a pint of ice cream most nights too. hence the hike this morning heh. ugh i just saw some tech bro with a tshirt that has a design that looks all too much like a tattoo i was planning to get. back to the drawing board.  
i’m tempted to ‘go out’ tonight and see what normal people do with their friday night. i went to ‘el rancho’ last friday and was cornered by this dude about my age just rambling on about his son and how he’d gotten laid at the same bar 18 years ago which is why his son was a green beret. he wasn’t drunk but might as well have been the way he was talking. this is what happens when i go out, some solo dude (always a dude) wants to talk my ear off on topics i couldn’t give a shit about. he was a nice enough guy, i shouldn’t be annoyed, i just wish i could have a substantial conversation with someone. i suppose not drinking when you’re at a bar draws a lot of the wrong kind of attention to you anyway, i shouldn’t be so surprised. 
just as soon as i leave the house i seem to want to get back home as soon as possible. this is obviously at odds with my imperative to meet new folks. i say imperative because its certainly not a desire. i’m pretty content being alone at this point, afterall, its been 5 years since i had a girlfriend and that was a shit show. 10 years since anything lasted longer than 8 months. ive told myself its largely to do with with work, always a good excuse… “ive been so busy with work!” but i have little to show for those efforts at the moment and less in terms of my personal life. should my work involve my personal life more intimately? folks who make that kind of intimate work always dance on the edge of cringe but others do it so well it brings you to tears, it does for me at least. 
i’m trying to think up the artists who really excel at that sort of intimate practice. musicians come up more quickly. arthur russel for sure, jason molina too. men who died young, shit. i should continue this list as method of charting some kind of new path for myself. wait wait i feel i landed on making intimate work a bit too soon. how intimate? i’m chuckling at myself at the moment realizing exactly why i have never made this kind of work… indecision and lack of intimacy in general. i have those raw nerves that tingle to shudder and i feel i am getting boring.
